Added some checks to templates/docker_registry/clean_registry_cron.erb

diff --git a/templates/docker_registry/clean_registry_cron.erb b/templates/docker_registry/clean_registry_cron.erb
--- a/templates/docker_registry/clean_registry_cron.erb
+++ b/templates/docker_registry/clean_registry_cron.erb
@@ -8,18 +8,28 @@ touch /etc/no-automatic-cosmos
 # Stop the Apache container so that no new requests
 # are made during the cleanup.
 docker stop registry-auth
+exit_status="${?}"
 
-# Start the actual cleanup
-/usr/local/bin/clean-registry/clean_registry.py /usr/local/bin/clean-registry/config_file.yaml
+if [[ "${exit_status}" = "0" ]]; then
+    # Start the actual cleanup
+    /usr/local/bin/clean-registry/clean_registry.py /usr/local/bin/clean-registry/config_file.yaml
+    exit_status="${?}"
+fi
 
-# A sleep before we start again might be good
-sleep 10
+if [[ "${exit_status}" = "0" ]]; then
+    # A sleep before we start again might be good
+    sleep 10
 
-# Run the garbage collection after removing layers
-docker exec -it registry /bin/registry garbage-collect /etc/docker/registry/config.yml
+    # Run the garbage collection after removing layers
+    docker exec -it registry /bin/registry garbage-collect /etc/docker/registry/config.yml
+    exit_status="${?}"
+fi
 
 # Start all the containers again.
 systemctl restart sunet-docker-registry
 
 # Enable cosmos again
 rm /etc/no-automatic-cosmos
+
+# Use the exit status from the commands we care about
+exit "${exit_status}"
