Import frontend from eduid_dev

diff --git a/templates/frontend/configure-container-network.erb b/templates/frontend/configure-container-network.erb
--- a/templates/frontend/configure-container-network.erb
+++ b/templates/frontend/configure-container-network.erb
@@ -60,7 +60,7 @@ ln -s /proc/${NSPID}/ns/net /var/run/netns/${INSTANCE}
 
 echo "Container ${CONTAINER}/${DOCKERID} has pid ${DOCKERPID} - symlinking /var/run/netns/${INSTANCE} to /proc/${NSPID}/ns/net"
 
-VETHHOST="${INSTANCE}"
+VETHHOST="to_${INSTANCE}"
 VETHCONTAINER="ve1${INSTANCE}"
 
 # Enable IPv6 forwarding. Should ideally be done more selectively, but...
@@ -69,23 +69,67 @@ sysctl net.ipv6.conf.all.forwarding=1
 set -x
 
 # Add a pair of virtual ethernet interfaces (think of them as a virtual cross-over ethernet cable)
-ip link del ${VETHHOST}
-ip link add name ${VETHHOST} mtu 1500 type veth peer name ${VETHCONTAINER} mtu 1500
-ip link set ${VETHHOST} master br-${INSTANCE}
-ip link set ${VETHHOST} up
+ip link del "${VETHHOST}"
+ip link add name "${VETHHOST}" mtu 1500 type veth peer name "${VETHCONTAINER}" mtu 1500
+if [ -f /var/run/netns/docker ]; then
+    # move VETHCONTAINER into the docker namespace and attach it to the bridge for this instance
+    ip link set "${VETHCONTAINER}" netns docker
+    ip -n docker link set "${VETHCONTAINER}" master "br-${INSTANCE}"
+else
+    ip link set "${VETHCONTAINER}" master "br-${INSTANCE}"
+fi
+ip link set "${VETHHOST}" up
 
+echo ""
+echo ""
+echo ""
 echo "$0: Network namespace and process diagnostics:"
 pgrep -a --ns "${DOCKERPID}"
 ip link show "${VETHHOST}"
-ip link show "${VETHCONTAINER}"
-ip link show "br-${INSTANCE}"
 
-# Move one end of the virtual ethernet cable inside the network namespace of the docker container
-ip link set "${VETHCONTAINER}" netns "${INSTANCE}" || {
-    echo "$0: FAILED to configure namespace, did ${CONTAINER} (pid ${DOCKERPID}) die?"
-    exit 1
-}
-ip netns exec "${INSTANCE}" ip link set "${VETHCONTAINER}" name sarimner0
+if [ -f /var/run/netns/docker ]; then
+    echo ""
+    echo ""
+    echo ""
+    echo "$0: Inside the docker namespace"
+    ip -n docker link show "${VETHCONTAINER}"
+    ip -n docker link show "br-${INSTANCE}"
+else
+    echo ""
+    echo ""
+    echo ""
+    echo "$0: In the host namespace"
+    ip link show "${VETHCONTAINER}"
+    ip link show "br-${INSTANCE}"
+fi
+
+echo ""
+echo ""
+echo ""
+echo "$0: Inside the instance namespace"
+ip -n "${INSTANCE}" link show "${VETHCONTAINER}"
+#ip -n "${INSTANCE}" link show "br-${INSTANCE}"
+
+if [ -f /var/run/netns/docker ]; then
+    # Move one end of the virtual ethernet cable from the docker namespace into the container namespace
+    ip -n docker link set "${VETHCONTAINER}" netns "${INSTANCE}" || {
+	echo "$0: FAILED to configure namespace, did ${CONTAINER} (pid ${DOCKERPID}) die?"
+	exit 1
+    }
+else
+    # Move one end of the virtual ethernet cable inside the network namespace of the docker container
+    ip link set "${VETHCONTAINER}" netns "${INSTANCE}" || {
+	echo "$0: FAILED to configure namespace, did ${CONTAINER} (pid ${DOCKERPID}) die?"
+	exit 1
+    }
+fi
+
+echo ""
+echo ""
+echo ""
+echo "$0: Renaming interface ${VETHCONTAINER} in the instance to sarimner0"
+# Rename interface inside container to sarimner0
+ip -n "${INSTANCE}" link set "${VETHCONTAINER}" name sarimner0
 
 # Docker likes to disable IPv6
 ip netns exec "${INSTANCE}" sysctl net.ipv6.conf.sarimner0.disable_ipv6=0
@@ -97,22 +141,89 @@ ip netns exec "${INSTANCE}" sysctl net.ipv6.conf.sarimner0.accept_dad=0
 # ip netns exec ${INSTANCE} sysctl net.ipv4.ip_nonlocal_bind=1
 # ip netns exec ${INSTANCE} sysctl net.ipv6.ip_nonlocal_bind=1
 
-
+echo ""
+echo ""
+echo ""
+echo "$0: Adding routing from host to the outside of the veth cable (${VETHHOST})"
 # Add IP addresses to the network namespace of the docker container
 for IP in $("${SCRIPTSDIR}"/frontend-config --instance "${INSTANCE}" print_ips); do
-    ip netns exec "${INSTANCE}" ip addr add "${IP}" dev sarimner0
-    ip route add "${IP}" dev br-"${INSTANCE}"
+    # The anycasted addresses are not suitable for use for outgoing connections. We can send packets
+    # just fine, but the responses may get routed to another frontend node. Therefore, we 'deprecate'
+    # them by setting preferred_lft to zero.
+    ip -n "${INSTANCE}" addr add "${IP}" dev sarimner0 preferred_lft 0
+    ip route add "${IP}" dev "${VETHHOST}"
 done
 
-ip netns exec "${INSTANCE}" ip link set sarimner0 up
+echo ""
+echo ""
+echo ""
+echo "$0: Bringing sarimner0 online, signalling the haproxy startup to commence"
+ip -n "${INSTANCE}" link set sarimner0 up
 
+# Set up routing for return traffic to the anycasted IPv4 addresses out through the sarimner0 inteface,
+# rather than to the Docker network namespace where it will be dropped.
+#
+# This requires source address based routing, fairly easy to do in a namespace fortunately.
+host_main_if=$(ip -4 route list | grep ^default | awk '{print $5}')
+v4gw=$(ip -4 -o addr list "${host_main_if}" | awk '{print $4}' | head -1 | awk -F / '{print $1}')
+v6gw=$(ip -6 -o addr list "${VETHHOST}" | awk '{print $4}' | head -1 | awk -F / '{print $1}')
+
+if [[ $v4gw ]]; then
+    ip -n "${INSTANCE}" -4 route add "${v4gw}" dev sarimner0 table 234
+    ip -n "${INSTANCE}" -4 route add default via "${v4gw}" dev sarimner0 table 234
+fi
+if [[ $v6gw ]]; then
+    ip -n "${INSTANCE}" -6 route add "${v6gw}" dev sarimner0 table 234
+    ip -n "${INSTANCE}" -6 route add default via "${v6gw}" dev sarimner0 table 234
+fi
+
+for IP in $("${SCRIPTSDIR}"/frontend-config --instance "${INSTANCE}" print_ips); do
+    if [[ $IP == *:* ]]; then
+        ip -n "${INSTANCE}" -6 rule add from "${IP}" table 234 prio 1
+    else
+        ip -n "${INSTANCE}" -4 rule add from "${IP}" table 234 prio 1
+    fi
+done
 
 # Set up IPv6 routing back out of the container, now that the interface is up.
 
 #sysctl net.ipv6.conf.${VETHHOST}.accept_dad=0
-v6gw=$(ip -6 addr list "br-${INSTANCE}" | awk '/inet6/{print $2}' | head -1 | awk -F / '{print $1}')
 if [[ $v6gw ]]; then
-    ip netns exec "${INSTANCE}" ip -6 route add default via "${v6gw}" dev sarimner0
+    ip -n "${INSTANCE}" -6 route add default via "${v6gw}" dev sarimner0
 else
     echo "$0: Can't set up IPv6 routing from container, device ${VETHHOST} has no IPv6 address"
 fi
+
+# Now add one more IPv6 address to sarimner0, within a prefix we can NAT suitably for
+# haproxy to be able to reach backends/acme-c etc. using IPv6
+extra_addr=$(ip -n "${INSTANCE}" -o addr show dev sarimner0 scope link | \
+    awk '{print $4'} | sed -e 's/^....::\(.*\)/fd0c::\1/')
+if [[ $extra_addr ]]; then
+    ip -n "${INSTANCE}" addr add "${extra_addr}" dev sarimner0
+    only_addr=$(echo ${extra_addr} | cut -d / -f 1)  # add host route, not with /64
+    ip route add "${only_addr}" dev "${VETHHOST}"
+else
+    echo "$0: Can't set up a IPv6 address for outgoing traffic from container, no link-local address found"
+fi
+
+echo ""
+echo ""
+echo ""
+echo "$0: Routing rules inside the instance namespace"
+ip -n "${INSTANCE}" -4 rule list
+ip -n "${INSTANCE}" -6 rule list
+echo ""
+echo ""
+echo ""
+echo "$0: General routes inside the instance namespace"
+ip -n "${INSTANCE}" -4 route list
+ip -n "${INSTANCE}" -6 route list
+echo ""
+echo ""
+echo ""
+echo "$0: Routes for the anycasted addresses inside the instance namespace"
+ip -n "${INSTANCE}" -4 route list table 234
+ip -n "${INSTANCE}" -6 route list table 234
+echo ""
+echo ""
+echo ""
